### PR TITLE
Linux SDK and documentation updated

### PR DESCRIPTION
**Pull request by mdmoo1978**
Updated linux-x86 and linux-x86_64 SDKs to 3.10.30003.5.
Added note to documentation about removing libatusb files, as they may interfere with Bitflow systems.

### CODE REVIEW

**Comment by MarkRivers** [comment]
In the documentation did you mean "may require" rather than "make require"?

**Comment by mdmoo1978** [comment]
Yes. Sorry typo.

**Comment by MarkRivers** [comment]
You can fix it before I merge the pull request.

Sent from my iPhone

On Apr 14, 2015, at 12:50 PM, mdmoo1978 <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes. Sorry typo.



> On Apr 14, 2015, at 2:45 PM, Mark Rivers <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> In the documentation did you mean "may require" rather than "make require"?
>
> �
> Reply to this email directly or view it on GitHub.
>

�

**Comment by mdmoo1978** [comment]
Was there anything else?

**Pull request merged**
